#!/bin/bash

pushd ..
cp -f feevee.db backup.db
popd
PYTHONASYNCIODEBUG=1 MONEY_CACHE=~/espial/money FEEVEE_SYMBOLS="VTI QQQ" FEEVEE_DB=backup.db uvicorn --log-config=`pwd`/logging.json --port 5000 --reload --factory "app:factory"
